-- 動作表

	ruFUSION_ACTORSTATE_NORMAL				= 0;
	ruFUSION_ACTORSTATE_JUMP				= 1;
	ruFUSION_ACTORSTATE_FALLING				= 2;
	ruFUSION_ACTORSTATE_SWIM_SURFACE		= 3;
	ruFUSION_ACTORSTATE_SWIM_DIVE			= 4;

	ruFUSION_ACTORSTATE_SIT_BEGIN			= 6;
	ruFUSION_ACTORSTATE_SIT_LOOP			= 7;
	ruFUSION_ACTORSTATE_SIT_END				= 8;

	ruFUSION_ACTORSTATE_SLEEP_BEGIN			= 9;
	ruFUSION_ACTORSTATE_SLEEP_LOOP			= 10;
	ruFUSION_ACTORSTATE_SLEEP_END			= 11;

	ruFUSION_ACTORSTATE_DYING				= 12;
	ruFUSION_ACTORSTATE_DEAD				= 13;
	ruFUSION_ACTORSTATE_REVIVING			= 14;

	ruFUSION_ACTORSTATE_SPAWN_BEGIN			= 15;
	ruFUSION_ACTORSTATE_SPAWN_END			= 16;

	ruFUSION_ACTORSTATE_CROUCH_BEGIN		= 148;
	ruFUSION_ACTORSTATE_CROUCH_LOOP			= 149;
	ruFUSION_ACTORSTATE_CROUCH_END			= 150;

	ruFUSION_ACTORSTATE_CRAFTING_BEGIN		= 131;
	ruFUSION_ACTORSTATE_CRAFTING_LOOP		= 132;
	ruFUSION_ACTORSTATE_CRAFTING_END		= 133;

	ruFUSION_ACTORSTATE_MINING_BEGIN		= 134;
	ruFUSION_ACTORSTATE_MINING_LOOP			= 135;
	ruFUSION_ACTORSTATE_MINING_END			= 136;
	ruFUSION_ACTORSTATE_MINING_END_HOLD		= 137;

	ruFUSION_ACTORSTATE_DAZED_BEGIN			= 138;
	ruFUSION_ACTORSTATE_DAZED_LOOP			= 139;
	ruFUSION_ACTORSTATE_DAZED_END			= 140;

	ruFUSION_ACTORSTATE_SLUMBER_BEGIN		= 141;
	ruFUSION_ACTORSTATE_SLUMBER_LOOP		= 142;
	ruFUSION_ACTORSTATE_SLUMBER_END			= 143;

	ruFUSION_ACTORSTATE_ACTIVATE_BEGIN		= 145;
	ruFUSION_ACTORSTATE_ACTIVATE_LOOP		= 146;
	ruFUSION_ACTORSTATE_ACTIVATE_END		= 147;

	ruFUSION_ACTORSTATE_READING_BEGIN		= 155;
	ruFUSION_ACTORSTATE_READING_LOOP		= 156;
	ruFUSION_ACTORSTATE_READING_END			= 157;

	ruFUSION_ACTORSTATE_KNOCKDOWN_BEGIN		= 181;
	ruFUSION_ACTORSTATE_KNOCKDOWN_LOOP		= 182;
	ruFUSION_ACTORSTATE_KNOCKDOWN_END		= 183;
	ruFUSION_ACTORSTATE_KNOCKDOWN_RECOVER	= 184;

	ruFUSION_ACTORSTATE_HOLDING				= 144;

	ruFUSION_ACTORSTATE_HURT_NORMAL			= 18;
	ruFUSION_ACTORSTATE_HURT_CRITICAL		= 19;
	ruFUSION_ACTORSTATE_DODGE				= 20;

	ruFUSION_ACTORSTATE_COMBAT_1H			= 21;	
	ruFUSION_ACTORSTATE_COMBAT_2H			= 22;	
	ruFUSION_ACTORSTATE_COMBAT_POLEARM		= 23;	
	ruFUSION_ACTORSTATE_COMBAT_UNARMED		= 24;	
	ruFUSION_ACTORSTATE_COMBAT_BOW			= 25;	
	ruFUSION_ACTORSTATE_COMBAT_GUN			= 26;	

	ruFUSION_ACTORSTATE_ATTACK_1H			= 31;	
	ruFUSION_ACTORSTATE_ATTACK_1H_SP		= 32;	
	ruFUSION_ACTORSTATE_ATTACK_1H_PIERCE	= 47;		
	ruFUSION_ACTORSTATE_ATTACK_2H			= 33;	
	ruFUSION_ACTORSTATE_ATTACK_2H_SP		= 34;	
	ruFUSION_ACTORSTATE_ATTACK_POLEARM		= 35;	
	ruFUSION_ACTORSTATE_ATTACK_POLEARM_SP	= 36;		
	ruFUSION_ACTORSTATE_ATTACK_UNARMED		= 37;	
	ruFUSION_ACTORSTATE_ATTACK_UNARMED_SP	= 38;		
	ruFUSION_ACTORSTATE_ATTACK_BOW_BEGIN	= 39;
	ruFUSION_ACTORSTATE_ATTACK_BOW_LOOP		= 40;
	ruFUSION_ACTORSTATE_ATTACK_BOW_END		= 41;
	ruFUSION_ACTORSTATE_ATTACK_GUN_BEGIN	= 42;
	ruFUSION_ACTORSTATE_ATTACK_GUN_LOOP		= 43;
	ruFUSION_ACTORSTATE_ATTACK_GUN_END		= 44;
	ruFUSION_ACTORSTATE_ATTACK_OH			= 45;	
	ruFUSION_ACTORSTATE_ATTACK_OH_PIERCE	= 46;		

	ruFUSION_ACTORSTATE_PARRY_1H			= 51;	
	ruFUSION_ACTORSTATE_PARRY_2H			= 52;	
	ruFUSION_ACTORSTATE_PARRY_BOW			= 53;
	ruFUSION_ACTORSTATE_PARRY_GUN			= 54;
	ruFUSION_ACTORSTATE_PARRY_POLEARM		= 55;
	ruFUSION_ACTORSTATE_PARRY_UNARMED		= 56;

	ruFUSION_ACTORSTATE_SHIELD_BASH			= 71;
	ruFUSION_ACTORSTATE_SHIELD_BLOCK		= 72;

	ruFUSION_ACTORSTATE_USE					= 75;
	ruFUSION_ACTORSTATE_THROW				= 76;

	ruFUSION_ACTORSTATE_BUFF_BEGIN			= 81;
	ruFUSION_ACTORSTATE_BUFF_LOOP			= 82;
	ruFUSION_ACTORSTATE_BUFF_END			= 83;
	ruFUSION_ACTORSTATE_BUFF_INSTANT		= 84;

	ruFUSION_ACTORSTATE_CAST_BEGIN			= 85;
	ruFUSION_ACTORSTATE_CAST_LOOP			= 86;
	ruFUSION_ACTORSTATE_CAST_END			= 87;
	ruFUSION_ACTORSTATE_CAST_INSTANT		= 88;

	ruFUSION_ACTORSTATE_CHANNEL_BEGIN		= 89;
	ruFUSION_ACTORSTATE_CHANNEL_LOOP		= 90;
	ruFUSION_ACTORSTATE_CHANNEL_END			= 91;
	ruFUSION_ACTORSTATE_CHANNEL_INSTANT		= 92;

	ruFUSION_ACTORSTATE_SP_SPINKICK			= 95;

	ruFUSION_ACTORSTATE_EMOTE_ANGRY			= 101;
	ruFUSION_ACTORSTATE_EMOTE_APPLAUSE		= 102;
	ruFUSION_ACTORSTATE_EMOTE_APPROVAL		= 103;
	ruFUSION_ACTORSTATE_EMOTE_BEG			= 104;
	ruFUSION_ACTORSTATE_EMOTE_CRY			= 105;
	ruFUSION_ACTORSTATE_EMOTE_HEAD_NOD		= 106;
	ruFUSION_ACTORSTATE_EMOTE_HEAD_SHAKE	= 107;
	ruFUSION_ACTORSTATE_EMOTE_LAUGH			= 108;
	ruFUSION_ACTORSTATE_EMOTE_POINT			= 109;
	ruFUSION_ACTORSTATE_EMOTE_PROVOKE		= 110;
	ruFUSION_ACTORSTATE_EMOTE_SALUTE		= 111;
	ruFUSION_ACTORSTATE_EMOTE_SPEAK			= 112;
	ruFUSION_ACTORSTATE_EMOTE_SURRENDER		= 113;
	ruFUSION_ACTORSTATE_EMOTE_THREATEN		= 114;
	ruFUSION_ACTORSTATE_EMOTE_VICTORY		= 115;
	ruFUSION_ACTORSTATE_EMOTE_WAVE			= 116;
	ruFUSION_ACTORSTATE_EMOTE_EAT			= 117;
	ruFUSION_ACTORSTATE_EMOTE_DRINK			= 118;
	ruFUSION_ACTORSTATE_EMOTE_IDLE			= 119;
	ruFUSION_ACTORSTATE_EMOTE_IDLE0			= 120;
	ruFUSION_ACTORSTATE_EMOTE_IDLE1			= 121;
	ruFUSION_ACTORSTATE_EMOTE_IDLE2			= 122;
	ruFUSION_ACTORSTATE_EMOTE_DANCE			= 123;

	ruFUSION_ACTORSTATE_HOLSTER				= 151;
	ruFUSION_ACTORSTATE_UNHOLSTER			= 152;
	ruFUSION_ACTORSTATE_HOLSTER_2H			= 153;
	ruFUSION_ACTORSTATE_UNHOLSTER_2H		= 154;


-- 裝備部位
EM_EQWearPos_Head       			= 0;
EM_EQWearPos_Gloves	    			= 1;
EM_EQWearPos_Shoes				= 2;
EM_EQWearPos_Clothes				= 3;
EM_EQWearPos_Pants				= 4;
EM_EQWearPos_Back				= 5;
EM_EQWearPos_Belt				= 6;
EM_EQWearPos_Shoulder				= 7;
EM_EQWearPos_Necklace   			= 8;
EM_EQWearPos_Ammo       			= 9;
EM_EQWearPos_Bow        			= 10;	
EM_EQWearPos_Ring1      			= 11;
EM_EQWearPos_Ring2      			= 12;
EM_EQWearPos_Earring1   			= 13;
EM_EQWearPos_Earring2   			= 14;
EM_EQWearPos_MainHand				= 15;
EM_EQWearPos_SecondHand 			= 16;
EM_EQWearPos_Manufactory			= 17;